import { describe, expect, it } from "vitest";
import { parseLuaData } from "../src/data/lua.js";

describe("parseLuaData", () => {
  it("parses a generated PoB-style table", () => {
    const src = `-- This file is automatically generated, do not edit!
-- Gem data (c) Grinding Gear Games

return {
	["Metadata/Items/Gems/SkillGemLeapSlam"] = {
		name = "Leap Slam",
		tags = {
			strength = true,
			melee = true,
		},
		weaponRequirements = "One Hand Mace, Two Hand Mace",
		reqStr = 100,
		Tier = 7,
	},
}`;
    expect(parseLuaData(src)).toEqual({
      "Metadata/Items/Gems/SkillGemLeapSlam": {
        name: "Leap Slam",
        tags: { strength: true, melee: true },
        weaponRequirements: "One Hand Mace, Two Hand Mace",
        reqStr: 100,
        Tier: 7,
      },
    });
  });

  it("turns positional tables into arrays", () => {
    expect(parseLuaData(`return { "a", "b"; 3 }`)).toEqual(["a", "b", 3]);
  });

  it("handles escapes, negatives, floats, nil and long strings", () => {
    expect(parseLuaData(`return { s = "a\\"b\\nc\\65", n = -1.5e2, z = nil, l = [[line
two]] }`)).toEqual({ s: 'a"b\ncA', n: -150, z: null, l: "line\ntwo" });
  });

  it("skips long comments", () => {
    expect(parseLuaData(`--[[ header
    ]] return { x = 1 }`)).toEqual({ x: 1 });
  });

  it("rejects code it doesn't understand", () => {
    expect(() => parseLuaData(`return { x = foo() }`)).toThrow();
  });
});
